import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Starting database seed...');

  // Delete all existing data in the correct order (respecting foreign keys)
  console.log('🗑️  Deleting existing order items...');
  await prisma.orderItem.deleteMany({});
  console.log('🗑️  Deleting existing orders...');
  await prisma.order.deleteMany({});
  console.log('🗑️  Deleting existing menu items...');
  await prisma.menuItem.deleteMany({});
  console.log('🗑️  Deleting existing venues...');
  await prisma.venue.deleteMany({});
  console.log('✅ Cleanup completed');

  // Create a property
  const property = await prisma.property.upsert({
    where: { id: '00000000-0000-0000-0000-000000000001' },
    update: {},
    create: {
      id: '00000000-0000-0000-0000-000000000001',
      name: 'Smart Living Hotel',
      address: '123 Luxury Avenue',
      city: 'New York',
      country: 'United States',
      description: 'A modern smart hotel with AI-powered services',
      image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&h=600&fit=crop',
    },
  });
  console.log('✅ Created property:', property.name);

  // Create service categories
  const categories = [
    { name: 'For You', slug: 'for-you', servicesDescription: 'Wellness & Fitness', order: 1 },
    { name: 'Restaurants', slug: 'restaurants', servicesDescription: 'Food & Drink', order: 2 },
    { name: 'Shops', slug: 'shops', servicesDescription: 'Shopping & Retail', order: 3 },
    { name: 'Transport', slug: 'transport', servicesDescription: 'Transportation Services', order: 4 },
    { name: 'Explore', slug: 'explore', servicesDescription: 'Attractions & Tours', order: 5 },
  ];

  const createdCategories: Record<string, { id: string; name: string }> = {};
  for (const category of categories) {
    const created = await prisma.serviceCategory.upsert({
      where: { slug: category.slug },
      update: {},
      create: category,
    });
    createdCategories[category.slug] = created;
  }
  console.log('✅ Created service categories');

  // Create venues
  const venues: Array<{
    name: string;
    type: 'RESTAURANT' | 'CAFE' | 'BAR' | 'SHOP' | 'SPA' | 'GYM' | 'TRANSPORT' | 'ATTRACTION';
    categorySlug: string;
    description: string;
    location: string;
    openingTime: string;
    closingTime: string;
    image?: string;
    phone?: string;
    latitude?: number;
    longitude?: number;
  }> = [
    // Restaurants
    {
      name: 'Bella Italia',
      type: 'RESTAURANT',
      categorySlug: 'restaurants',
      description: 'Authentic Italian cuisine featuring handmade pasta, wood-fired pizzas, and traditional recipes from Rome to Sicily',
      location: 'Ground Floor, West Wing',
      openingTime: '11:00',
      closingTime: '23:00',
      image: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=400&h=400&fit=crop',
      phone: '+1 (212) 555-0101',
      latitude: 40.758896,
      longitude: -73.985130,
    },
    {
      name: 'Tokyo Kitchen',
      type: 'RESTAURANT',
      categorySlug: 'restaurants',
      description: 'Fresh sushi, sashimi, and traditional Japanese dishes prepared by master chefs with 20+ years experience',
      location: 'Ground Floor, East Wing',
      openingTime: '12:00',
      closingTime: '22:00',
      image: 'https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=400&h=400&fit=crop',
      phone: '+1 (212) 555-0102',
      latitude: 40.759123,
      longitude: -73.984890,
    },
    {
      name: 'The Burger Lab',
      type: 'RESTAURANT',
      categorySlug: 'restaurants',
      description: 'Gourmet burgers crafted with premium Angus beef, organic vegetables, and artisan buns paired with craft beers',
      location: '2nd Floor, Food Court',
      openingTime: '11:00',
      closingTime: '22:00',
      image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400&h=400&fit=crop',
      phone: '+1 (212) 555-0103',
      latitude: 40.758756,
      longitude: -73.985456,
    },
    {
      name: 'Le Bistro Français',
      type: 'RESTAURANT',
      categorySlug: 'restaurants',
      description: 'Classic French bistro serving coq au vin, duck confit, and an extensive wine collection',
      location: '1st Floor, Garden View',
      openingTime: '12:00',
      closingTime: '23:00',
      image: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=400&h=400&fit=crop',
      phone: '+1 (212) 555-0115',
      latitude: 40.758723,
      longitude: -73.985423,
    },
    {
      name: 'Spice Route',
      type: 'RESTAURANT',
      categorySlug: 'restaurants',
      description: 'Authentic Indian cuisine with tandoori specialties, curries, and vegetarian options',
      location: '2nd Floor, South Wing',
      openingTime: '11:30',
      closingTime: '22:30',
      image: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400&h=400&fit=crop',
      phone: '+1 (212) 555-0116',
      latitude: 40.758567,
      longitude: -73.985678,
    },
    // Cafes
    {
      name: 'The Elah Lounge',
      type: 'CAFE',
      categorySlug: 'restaurants',
      description: 'Premium breakfast and brunch destination with artisan coffee, fresh pastries, and healthy options',
      location: 'Ground Floor, Main Lobby',
      openingTime: '06:00',
      closingTime: '14:00',
      image: 'https://images.unsplash.com/photo-1533777857889-4be7c70b33f7?w=400&h=400&fit=crop',
      phone: '+1 (212) 555-0100',
      latitude: 40.758634,
      longitude: -73.985312,
    },
    {
      name: 'Café Mocha',
      type: 'CAFE',
      categorySlug: 'restaurants',
      description: 'Specialty coffee house with single-origin beans, homemade cakes, and light bites',
      location: 'Mezzanine Level',
      openingTime: '07:00',
      closingTime: '20:00',
      image: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=400&h=400&fit=crop',
      phone: '+1 (212) 555-0117',
      latitude: 40.758890,
      longitude: -73.985234,
    },
    // Bars
    {
      name: 'Skybar Lounge',
      type: 'BAR',
      categorySlug: 'restaurants',
      description: 'Rooftop bar with signature cocktails, premium spirits, and breathtaking 360° city views',
      location: 'Rooftop, 15th Floor',
      openingTime: '17:00',
      closingTime: '02:00',
      image: 'https://images.unsplash.com/photo-1514933651103-005eec06c04b?w=400&h=400&fit=crop',
      phone: '+1 (212) 555-0106',
      latitude: 40.758912,
      longitude: -73.985234,
    },
    {
      name: 'The Wine Cellar',
      type: 'BAR',
      categorySlug: 'restaurants',
      description: 'Intimate wine bar featuring over 200 international wines and gourmet cheese selections',
      location: 'Lower Level',
      openingTime: '16:00',
      closingTime: '00:00',
      image: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=400&h=400&fit=crop',
      phone: '+1 (212) 555-0118',
      latitude: 40.758445,
      longitude: -73.985567,
    },
    // Shops
    {
      name: 'Fresh Market',
      type: 'SHOP',
      categorySlug: 'shops',
      description: 'Organic fresh produce, artisan bread, imported cheeses, and gourmet daily essentials',
      location: 'Lobby Level, North Side',
      openingTime: '07:00',
      closingTime: '22:00',
      image: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=400&h=400&fit=crop',
      phone: '+1 (212) 555-0104',
      latitude: 40.758789,
      longitude: -73.985678,
    },
    {
      name: '24/7 Convenience Store',
      type: 'SHOP',
      categorySlug: 'shops',
      description: 'Quick snacks, beverages, toiletries, and everyday convenience items available round the clock',
      location: 'Lobby Level, South Corner',
      openingTime: '00:00',
      closingTime: '23:59',
      image: 'https://images.unsplash.com/photo-1604719312566-8912e9227c6a?w=400&h=400&fit=crop',
      phone: '+1 (212) 555-0105',
      latitude: 40.758567,
      longitude: -73.985890,
    },
    {
      name: 'Luxury Boutique',
      type: 'SHOP',
      categorySlug: 'shops',
      description: 'Designer fashion, luxury accessories, jewelry, and exclusive hotel branded merchandise',
      location: '1st Floor, Shopping Gallery',
      openingTime: '10:00',
      closingTime: '20:00',
      image: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=400&h=400&fit=crop',
      phone: '+1 (212) 555-0107',
      latitude: 40.758445,
      longitude: -73.985745,
    },
    {
      name: 'Tech & Travel',
      type: 'SHOP',
      categorySlug: 'shops',
      description: 'Electronics, chargers, adapters, luggage, and essential travel accessories',
      location: 'Lobby Level, East Corridor',
      openingTime: '08:00',
      closingTime: '21:00',
      image: 'https://images.unsplash.com/photo-1601524909162-ae8725290836?w=400&h=400&fit=crop',
      phone: '+1 (212) 555-0119',
      latitude: 40.758678,
      longitude: -73.985901,
    },
    // Wellness
    {
      name: 'Serenity Spa',
      type: 'SPA',
      categorySlug: 'for-you',
      description: 'Full-service luxury spa offering massage therapy, facials, body treatments, and holistic wellness services',
      location: '3rd Floor, Wellness Center',
      openingTime: '08:00',
      closingTime: '21:00',
      image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=400&h=400&fit=crop',
      phone: '+1 (212) 555-0108',
      latitude: 40.758923,
      longitude: -73.985567,
    },
    {
      name: 'Fitness Center',
      type: 'GYM',
      categorySlug: 'for-you',
      description: 'State-of-the-art gym with cardio equipment, free weights, personal trainers, and group fitness classes',
      location: '3rd Floor, Wellness Center',
      openingTime: '05:00',
      closingTime: '23:00',
      image: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400&h=400&fit=crop',
      phone: '+1 (212) 555-0109',
      latitude: 40.758856,
      longitude: -73.985423,
    },
    {
      name: 'Yoga & Meditation Studio',
      type: 'GYM',
      categorySlug: 'for-you',
      description: 'Peaceful studio offering yoga, meditation, pilates, and mindfulness classes for all levels',
      location: '3rd Floor, West Wing',
      openingTime: '06:00',
      closingTime: '21:00',
      image: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=400&h=400&fit=crop',
      phone: '+1 (212) 555-0120',
      latitude: 40.758734,
      longitude: -73.985312,
    },
    // Transport
    {
      name: 'Concierge Desk',
      type: 'TRANSPORT',
      categorySlug: 'transport',
      description: 'Premium car service, luxury vehicle rentals, taxi arrangements, and airport transfers with meet & greet',
      location: 'Main Lobby',
      openingTime: '00:00',
      closingTime: '23:59',
      image: 'https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=400&h=400&fit=crop',
      phone: '+1 (212) 555-0110',
      latitude: 40.758701,
      longitude: -73.985234,
    },
    {
      name: 'Bike Rentals',
      type: 'TRANSPORT',
      categorySlug: 'transport',
      description: 'E-bikes, city bikes, and guided cycling tours around the city with maps and safety gear included',
      location: 'Ground Floor, Rear Entrance',
      openingTime: '07:00',
      closingTime: '20:00',
      image: 'https://images.unsplash.com/photo-1571333250630-f0230c320b6d?w=400&h=400&fit=crop',
      phone: '+1 (212) 555-0121',
      latitude: 40.758512,
      longitude: -73.985876,
    },
    // Explore
    {
      name: 'City Tours & Tickets',
      type: 'ATTRACTION',
      categorySlug: 'explore',
      description: 'Guided city tours, museum tickets, theater bookings, and curated local experiences',
      location: 'Main Lobby, Tour Desk',
      openingTime: '07:00',
      closingTime: '20:00',
      image: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=400&h=400&fit=crop',
      phone: '+1 (212) 555-0111',
      latitude: 40.758678,
      longitude: -73.985189,
    },
    {
      name: 'Cultural Experiences',
      type: 'ATTRACTION',
      categorySlug: 'explore',
      description: 'Exclusive access to art galleries, cooking classes, wine tastings, and authentic local experiences',
      location: '1st Floor, Experience Center',
      openingTime: '09:00',
      closingTime: '19:00',
      image: 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=400&h=400&fit=crop',
      phone: '+1 (212) 555-0122',
      latitude: 40.758823,
      longitude: -73.985445,
    },
  ];

  const createdVenues: { id: string; name: string }[] = [];
  for (const venueData of venues) {
    const { categorySlug, ...rest } = venueData;
    const venue = await prisma.venue.create({
      data: {
        ...rest,
        propertyId: property.id,
        categoryId: createdCategories[categorySlug].id,
      },
    });
    createdVenues.push(venue);
  }
  console.log('✅ Created venues');

  // Create menu items for The Elah Lounge and other restaurants
  const menuItems = [
    // The Elah Lounge - Breakfast & Brunch
    {
      venueName: 'The Elah Lounge',
      name: 'Pancake Stack',
      description: 'Fluffy buttermilk pancakes with maple syrup, fresh berries, and whipped butter',
      price: 12.99,
      category: 'Breakfast',
      image: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=400&h=600&fit=crop',
      allergens: ['Gluten', 'Dairy', 'Eggs'],
    },
    {
      venueName: 'The Elah Lounge',
      name: 'Avocado Toast',
      description: 'Sourdough toast with smashed avocado, poached egg, cherry tomatoes, and microgreens',
      price: 14.99,
      category: 'Breakfast',
      image: 'https://images.unsplash.com/photo-1541519227354-08fa5d50c44d?w=400&h=600&fit=crop',
      allergens: ['Gluten', 'Eggs'],
    },
    {
      venueName: 'The Elah Lounge',
      name: 'Classic Eggs Benedict',
      description: 'Poached eggs on English muffin with Canadian bacon and hollandaise sauce',
      price: 16.99,
      category: 'Breakfast',
      image: 'https://images.unsplash.com/photo-1608039755401-742074f0548d?w=400&h=600&fit=crop',
      allergens: ['Gluten', 'Eggs', 'Dairy'],
    },
    {
      venueName: 'The Elah Lounge',
      name: 'French Croissant',
      description: 'Buttery flaky croissant with choice of strawberry jam, orange marmalade, or Nutella',
      price: 6.99,
      category: 'Pastries',
      image: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=400&h=600&fit=crop',
      allergens: ['Gluten', 'Dairy'],
    },
    {
      venueName: 'The Elah Lounge',
      name: 'Greek Yogurt Parfait',
      description: 'Thick Greek yogurt layered with honey, granola, fresh berries, and almonds',
      price: 10.99,
      category: 'Breakfast',
      image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400&h=600&fit=crop',
      allergens: ['Dairy', 'Nuts'],
    },
    {
      venueName: 'The Elah Lounge',
      name: 'Smoked Salmon Bagel',
      description: 'Fresh bagel with cream cheese, smoked salmon, capers, red onion, and dill',
      price: 15.99,
      category: 'Breakfast',
      image: 'https://images.unsplash.com/photo-1619096252214-ef06c45683e3?w=400&h=600&fit=crop',
      allergens: ['Gluten', 'Dairy', 'Fish'],
    },
    {
      venueName: 'The Elah Lounge',
      name: 'Cappuccino',
      description: 'Double shot espresso with velvety steamed milk foam and cocoa dusting',
      price: 5.50,
      category: 'Beverages',
      image: 'https://images.unsplash.com/photo-1572442388796-11668a67e53d?w=400&h=600&fit=crop',
      allergens: ['Dairy'],
    },
    {
      venueName: 'The Elah Lounge',
      name: 'Fresh Orange Juice',
      description: 'Freshly squeezed orange juice, no added sugar',
      price: 6.99,
      category: 'Beverages',
      image: 'https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=400&h=600&fit=crop',
      allergens: [],
    },
    // Bella Italia - Italian Restaurant
    {
      venueName: 'Bella Italia',
      name: 'Pizza Margherita',
      description: 'Classic Neapolitan pizza with San Marzano tomatoes, fresh mozzarella di bufala, and basil',
      price: 16.99,
      category: 'Pizza',
      image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=400&h=600&fit=crop',
      allergens: ['Gluten', 'Dairy'],
    },
    {
      venueName: 'Bella Italia',
      name: 'Truffle Mushroom Pizza',
      description: 'White pizza with mixed mushrooms, truffle oil, mozzarella, and fresh arugula',
      price: 21.99,
      category: 'Pizza',
      image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=400&h=600&fit=crop',
      allergens: ['Gluten', 'Dairy'],
    },
    {
      venueName: 'Bella Italia',
      name: 'Pasta Carbonara',
      description: 'Creamy pasta with crispy pancetta, eggs, pecorino romano, and cracked black pepper',
      price: 18.99,
      category: 'Pasta',
      image: 'https://images.unsplash.com/photo-1612874742237-6526221588e3?w=400&h=600&fit=crop',
      allergens: ['Gluten', 'Dairy', 'Eggs'],
    },
    {
      venueName: 'Bella Italia',
      name: 'Spaghetti Bolognese',
      description: 'Traditional meat sauce with San Marzano tomatoes, herbs, and parmesan',
      price: 17.99,
      category: 'Pasta',
      image: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=400&h=600&fit=crop',
      allergens: ['Gluten', 'Dairy'],
    },
    {
      venueName: 'Bella Italia',
      name: 'Linguine alle Vongole',
      description: 'Fresh clams with white wine, garlic, parsley, and extra virgin olive oil',
      price: 22.99,
      category: 'Pasta',
      image: 'https://images.unsplash.com/photo-1563379091339-03b47dad04f9?w=400&h=600&fit=crop',
      allergens: ['Gluten', 'Shellfish'],
    },
    {
      venueName: 'Bella Italia',
      name: 'Osso Buco',
      description: 'Braised veal shanks with gremolata, served with creamy saffron risotto',
      price: 32.99,
      category: 'Main Course',
      image: 'https://images.unsplash.com/photo-1633964913295-ceb43826e36b?w=400&h=600&fit=crop',
      allergens: ['Dairy'],
    },
    {
      venueName: 'Bella Italia',
      name: 'Bruschetta Trio',
      description: 'Three variations: classic tomato, olive tapenade, and roasted red pepper',
      price: 9.99,
      category: 'Appetizers',
      image: 'https://images.unsplash.com/photo-1572695157366-5e585ab2b69f?w=400&h=600&fit=crop',
      allergens: ['Gluten'],
    },
    {
      venueName: 'Bella Italia',
      name: 'Caprese Salad',
      description: 'Fresh mozzarella, heirloom tomatoes, basil, balsamic reduction, and olive oil',
      price: 12.99,
      category: 'Appetizers',
      image: 'https://images.unsplash.com/photo-1608897013039-887f21d8c804?w=400&h=600&fit=crop',
      allergens: ['Dairy'],
    },
    {
      venueName: 'Bella Italia',
      name: 'Tiramisu',
      description: 'Classic Italian dessert with espresso-soaked ladyfingers, mascarpone, and cocoa',
      price: 8.99,
      category: 'Desserts',
      image: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=400&h=600&fit=crop',
      allergens: ['Gluten', 'Dairy', 'Eggs'],
    },
    {
      venueName: 'Bella Italia',
      name: 'Panna Cotta',
      description: 'Silky vanilla cream with mixed berry compote',
      price: 7.99,
      category: 'Desserts',
      image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400&h=600&fit=crop',
      allergens: ['Dairy'],
    },
    // Tokyo Kitchen - Japanese Restaurant
    {
      venueName: 'Tokyo Kitchen',
      name: 'Chef\'s Sushi Platter',
      description: 'Assorted premium nigiri and sashimi with wasabi, pickled ginger, and soy sauce',
      price: 32.99,
      category: 'Sushi',
      image: 'https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=400&h=600&fit=crop',
      allergens: ['Fish', 'Soy'],
    },
    {
      venueName: 'Tokyo Kitchen',
      name: 'Dragon Roll',
      description: 'Shrimp tempura, avocado, topped with eel and spicy mayo',
      price: 16.99,
      category: 'Sushi',
      image: 'https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=400&h=600&fit=crop',
      allergens: ['Fish', 'Shellfish', 'Gluten', 'Eggs'],
    },
    {
      venueName: 'Tokyo Kitchen',
      name: 'Salmon Sashimi',
      description: 'Fresh Atlantic salmon sliced sashimi-style with daikon radish',
      price: 18.99,
      category: 'Sushi',
      image: 'https://images.unsplash.com/photo-1583623025817-d180a2221d0a?w=400&h=600&fit=crop',
      allergens: ['Fish'],
    },
    {
      venueName: 'Tokyo Kitchen',
      name: 'Tonkotsu Ramen',
      description: 'Rich pork bone broth with chashu pork, soft-boiled egg, bamboo shoots, and noodles',
      price: 15.99,
      category: 'Ramen',
      image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=400&h=600&fit=crop',
      allergens: ['Gluten', 'Eggs', 'Soy'],
    },
    {
      venueName: 'Tokyo Kitchen',
      name: 'Spicy Miso Ramen',
      description: 'Miso broth with ground pork, corn, bean sprouts, and chili oil',
      price: 16.99,
      category: 'Ramen',
      image: 'https://images.unsplash.com/photo-1617093727343-374698b1b08d?w=400&h=600&fit=crop',
      allergens: ['Gluten', 'Soy'],
    },
    {
      venueName: 'Tokyo Kitchen',
      name: 'Chicken Teriyaki',
      description: 'Grilled chicken with house-made teriyaki sauce, steamed rice, and seasonal vegetables',
      price: 17.99,
      category: 'Main Course',
      image: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=400&h=600&fit=crop',
      allergens: ['Soy', 'Gluten'],
    },
    {
      venueName: 'Tokyo Kitchen',
      name: 'Wagyu Beef Teppanyaki',
      description: 'Premium Japanese wagyu beef grilled to perfection with garlic butter',
      price: 42.99,
      category: 'Main Course',
      image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=400&h=600&fit=crop',
      allergens: ['Soy', 'Dairy'],
    },
    {
      venueName: 'Tokyo Kitchen',
      name: 'Edamame',
      description: 'Steamed young soybeans with sea salt',
      price: 5.99,
      category: 'Appetizers',
      image: 'https://images.unsplash.com/photo-1583755782347-83f18c0e7d14?w=400&h=600&fit=crop',
      allergens: ['Soy'],
    },
    {
      venueName: 'Tokyo Kitchen',
      name: 'Gyoza',
      description: 'Pan-fried pork dumplings with soy-vinegar dipping sauce',
      price: 8.99,
      category: 'Appetizers',
      image: 'https://images.unsplash.com/photo-1496116218417-1a781b1c416c?w=400&h=600&fit=crop',
      allergens: ['Gluten', 'Soy'],
    },
    {
      venueName: 'Tokyo Kitchen',
      name: 'Mochi Ice Cream',
      description: 'Japanese rice cake with green tea, mango, or red bean ice cream',
      price: 7.99,
      category: 'Desserts',
      image: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=400&h=600&fit=crop',
      allergens: ['Dairy'],
    },
    // The Burger Lab
    {
      venueName: 'The Burger Lab',
      name: 'Signature Wagyu Burger',
      description: 'Premium wagyu beef with aged cheddar, truffle aioli, caramelized onions, and arugula',
      price: 22.99,
      category: 'Burgers',
      image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=400&h=600&fit=crop',
      allergens: ['Gluten', 'Dairy', 'Eggs'],
    },
    {
      venueName: 'The Burger Lab',
      name: 'Classic Beef Burger',
      description: 'Angus beef, lettuce, tomato, pickles, onions, and house sauce',
      price: 16.99,
      category: 'Burgers',
      image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400&h=400&fit=crop',
      allergens: ['Gluten', 'Eggs'],
    },
    {
      venueName: 'The Burger Lab',
      name: 'Crispy Chicken Burger',
      description: 'Buttermilk fried chicken breast with coleslaw, pickles, and spicy mayo',
      price: 15.99,
      category: 'Burgers',
      image: 'https://images.unsplash.com/photo-1606755962773-d324e0a13086?w=400&h=600&fit=crop',
      allergens: ['Gluten', 'Eggs', 'Dairy'],
    },
    {
      venueName: 'The Burger Lab',
      name: 'Veggie Beyond Burger',
      description: 'Plant-based patty with avocado, sprouts, tomato, and vegan aioli',
      price: 14.99,
      category: 'Burgers',
      image: 'https://images.unsplash.com/photo-1520072959219-c595dc870360?w=400&h=600&fit=crop',
      allergens: ['Gluten', 'Soy'],
    },
    {
      venueName: 'The Burger Lab',
      name: 'Truffle Parmesan Fries',
      description: 'Crispy fries tossed with truffle oil, parmesan cheese, and fresh herbs',
      price: 8.99,
      category: 'Sides',
      image: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=400&h=600&fit=crop',
      allergens: ['Dairy'],
    },
    {
      venueName: 'The Burger Lab',
      name: 'Sweet Potato Fries',
      description: 'Crispy sweet potato fries with chipotle mayo',
      price: 7.99,
      category: 'Sides',
      image: 'https://images.unsplash.com/photo-1639024471283-03518883512d?w=400&h=600&fit=crop',
      allergens: ['Eggs'],
    },
    {
      venueName: 'The Burger Lab',
      name: 'Onion Rings',
      description: 'Beer-battered crispy onion rings with ranch dressing',
      price: 7.99,
      category: 'Sides',
      image: 'https://images.unsplash.com/photo-1639024471283-03518883512d?w=400&h=600&fit=crop',
      allergens: ['Gluten', 'Eggs', 'Dairy'],
    },
    {
      venueName: 'The Burger Lab',
      name: 'Craft Beer Flight',
      description: 'Selection of four seasonal craft beers (12oz total)',
      price: 18.99,
      category: 'Beverages',
      image: 'https://images.unsplash.com/photo-1608270586620-248524c67de9?w=400&h=600&fit=crop',
      allergens: ['Gluten'],
    },
    {
      venueName: 'The Burger Lab',
      name: 'Chocolate Milkshake',
      description: 'Thick and creamy chocolate shake with whipped cream and chocolate shavings',
      price: 7.99,
      category: 'Desserts',
      image: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=400&h=600&fit=crop',
      allergens: ['Dairy'],
    },
    // Le Bistro Français
    {
      venueName: 'Le Bistro Français',
      name: 'Coq au Vin',
      description: 'Braised chicken in red wine with mushrooms, pearl onions, and bacon',
      price: 26.99,
      category: 'Main Course',
      image: 'https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=400&h=600&fit=crop',
      allergens: ['Dairy'],
    },
    {
      venueName: 'Le Bistro Français',
      name: 'Duck Confit',
      description: 'Slow-cooked duck leg with roasted potatoes and green beans',
      price: 29.99,
      category: 'Main Course',
      image: 'https://images.unsplash.com/photo-1625938145744-e380515399af?w=400&h=600&fit=crop',
      allergens: [],
    },
    {
      venueName: 'Le Bistro Français',
      name: 'Steak Frites',
      description: 'Grilled ribeye steak with herb butter and crispy French fries',
      price: 32.99,
      category: 'Main Course',
      image: 'https://images.unsplash.com/photo-1600891964092-4316c288032e?w=400&h=600&fit=crop',
      allergens: ['Dairy'],
    },
    {
      venueName: 'Le Bistro Français',
      name: 'French Onion Soup',
      description: 'Traditional soup with caramelized onions, gruyère cheese, and toasted baguette',
      price: 12.99,
      category: 'Appetizers',
      image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=400&h=600&fit=crop',
      allergens: ['Gluten', 'Dairy'],
    },
    {
      venueName: 'Le Bistro Français',
      name: 'Escargots de Bourgogne',
      description: 'Snails in garlic-herb butter with crusty bread',
      price: 14.99,
      category: 'Appetizers',
      image: 'https://images.unsplash.com/photo-1563379091339-03b47dad04f9?w=400&h=600&fit=crop',
      allergens: ['Gluten', 'Dairy'],
    },
    {
      venueName: 'Le Bistro Français',
      name: 'Crème Brûlée',
      description: 'Classic vanilla custard with caramelized sugar crust',
      price: 9.99,
      category: 'Desserts',
      image: 'https://images.unsplash.com/photo-1470124182917-cc6e71b22ecc?w=400&h=600&fit=crop',
      allergens: ['Dairy', 'Eggs'],
    },
    // Spice Route - Indian
    {
      venueName: 'Spice Route',
      name: 'Butter Chicken',
      description: 'Tender chicken in creamy tomato sauce with aromatic spices',
      price: 18.99,
      category: 'Main Course',
      image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=400&h=600&fit=crop',
      allergens: ['Dairy'],
    },
    {
      venueName: 'Spice Route',
      name: 'Lamb Rogan Josh',
      description: 'Slow-cooked lamb in rich curry sauce with Kashmiri spices',
      price: 22.99,
      category: 'Main Course',
      image: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400&h=600&fit=crop',
      allergens: ['Dairy'],
    },
    {
      venueName: 'Spice Route',
      name: 'Palak Paneer',
      description: 'Cottage cheese cubes in creamy spinach curry',
      price: 16.99,
      category: 'Vegetarian',
      image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=400&h=600&fit=crop',
      allergens: ['Dairy'],
    },
    {
      venueName: 'Spice Route',
      name: 'Tandoori Mixed Grill',
      description: 'Assorted meats marinated in yogurt and spices, cooked in tandoor',
      price: 24.99,
      category: 'Main Course',
      image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=400&h=600&fit=crop',
      allergens: ['Dairy'],
    },
    {
      venueName: 'Spice Route',
      name: 'Garlic Naan',
      description: 'Freshly baked flatbread with garlic and butter',
      price: 4.99,
      category: 'Breads',
      image: 'https://images.unsplash.com/photo-1619365856398-c3c7f0f6f2c5?w=400&h=600&fit=crop',
      allergens: ['Gluten', 'Dairy'],
    },
    {
      venueName: 'Spice Route',
      name: 'Mango Lassi',
      description: 'Sweet yogurt drink blended with fresh mango',
      price: 5.99,
      category: 'Beverages',
      image: 'https://images.unsplash.com/photo-1623231794251-cd74adc5284e?w=400&h=600&fit=crop',
      allergens: ['Dairy'],
    },
    // Skybar Lounge - Cocktails
    {
      venueName: 'Skybar Lounge',
      name: 'Cosmopolitan',
      description: 'Vodka, cranberry, lime, and triple sec with orange twist',
      price: 14.99,
      category: 'Cocktails',
      image: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=400&h=600&fit=crop',
      allergens: [],
    },
    {
      venueName: 'Skybar Lounge',
      name: 'Old Fashioned',
      description: 'Bourbon whiskey with bitters, sugar, and orange twist',
      price: 16.99,
      category: 'Cocktails',
      image: 'https://images.unsplash.com/photo-1470337458703-46ad1756a187?w=400&h=600&fit=crop',
      allergens: [],
    },
    {
      venueName: 'Skybar Lounge',
      name: 'Mojito',
      description: 'White rum, fresh mint, lime, sugar, and soda water',
      price: 13.99,
      category: 'Cocktails',
      image: 'https://images.unsplash.com/photo-1551538827-9c037cb4f32a?w=400&h=600&fit=crop',
      allergens: [],
    },
    {
      venueName: 'Skybar Lounge',
      name: 'Espresso Martini',
      description: 'Vodka, coffee liqueur, and fresh espresso',
      price: 15.99,
      category: 'Cocktails',
      image: 'https://images.unsplash.com/photo-1536599018102-9f803c140fc1?w=400&h=600&fit=crop',
      allergens: [],
    },
    {
      venueName: 'Skybar Lounge',
      name: 'Spanish Tapas Platter',
      description: 'Assorted olives, manchego cheese, jamón ibérico, and crusty bread',
      price: 24.99,
      category: 'Food',
      image: 'https://images.unsplash.com/photo-1541529086526-db283c563270?w=400&h=600&fit=crop',
      allergens: ['Gluten', 'Dairy'],
    },
    {
      venueName: 'Skybar Lounge',
      name: 'Truffle Fries',
      description: 'Crispy fries with truffle oil and parmesan',
      price: 12.99,
      category: 'Food',
      image: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=400&h=600&fit=crop',
      allergens: ['Dairy'],
    },
    // Café Mocha
    {
      venueName: 'Café Mocha',
      name: 'Caramel Macchiato',
      description: 'Espresso with vanilla, steamed milk, and caramel drizzle',
      price: 6.50,
      category: 'Coffee',
      image: 'https://images.unsplash.com/photo-1579954115545-a95591f28bfc?w=400&h=600&fit=crop',
      allergens: ['Dairy'],
    },
    {
      venueName: 'Café Mocha',
      name: 'New York Cheesecake',
      description: 'Creamy classic cheesecake with graham cracker crust',
      price: 8.99,
      category: 'Desserts',
      image: 'https://images.unsplash.com/photo-1524351199678-941a58a3df50?w=400&h=600&fit=crop',
      allergens: ['Gluten', 'Dairy', 'Eggs'],
    },
    {
      venueName: 'Café Mocha',
      name: 'Chocolate Brownie',
      description: 'Fudgy chocolate brownie with vanilla ice cream',
      price: 7.99,
      category: 'Desserts',
      image: 'https://images.unsplash.com/photo-1607920591413-4ec007e70023?w=400&h=600&fit=crop',
      allergens: ['Gluten', 'Dairy', 'Eggs'],
    },
    // Fresh Market
    {
      venueName: 'Fresh Market',
      name: 'Caesar Salad',
      description: 'Romaine lettuce, parmesan, croutons, and house-made Caesar dressing',
      price: 11.99,
      category: 'Salads',
      image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400&h=600&fit=crop',
      allergens: ['Gluten', 'Dairy', 'Fish', 'Eggs'],
    },
    {
      venueName: 'Fresh Market',
      name: 'Quinoa Power Bowl',
      description: 'Quinoa with roasted vegetables, chickpeas, avocado, and tahini dressing',
      price: 13.99,
      category: 'Bowls',
      image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400&h=600&fit=crop',
      allergens: ['Sesame'],
    },
    {
      venueName: 'Fresh Market',
      name: 'Acai Bowl',
      description: 'Acai berries topped with granola, fresh fruit, and honey',
      price: 12.99,
      category: 'Bowls',
      image: 'https://images.unsplash.com/photo-1590301157890-4810ed352733?w=400&h=600&fit=crop',
      allergens: ['Nuts'],
    },
    {
      venueName: 'Fresh Market',
      name: 'Green Detox Smoothie',
      description: 'Spinach, kale, banana, mango, and coconut water',
      price: 8.99,
      category: 'Beverages',
      image: 'https://images.unsplash.com/photo-1610970881699-44a5587cabec?w=400&h=600&fit=crop',
      allergens: [],
    },
    {
      venueName: 'Fresh Market',
      name: 'Protein Power Smoothie',
      description: 'Banana, peanut butter, protein powder, and almond milk',
      price: 9.99,
      category: 'Beverages',
      image: 'https://images.unsplash.com/photo-1638176066666-ffb2f013c7dd?w=400&h=600&fit=crop',
      allergens: ['Nuts'],
    },
  ];

  for (const item of menuItems) {
    const venue = createdVenues.find((v) => v.name === item.venueName);
    if (venue) {
      await prisma.menuItem.create({
        data: {
          venueId: venue.id,
          name: item.name,
          description: item.description,
          price: item.price,
          category: item.category,
          image: item.image,
          allergens: item.allergens,
          isAvailable: true,
        },
      });
    }
  }
  console.log('✅ Created menu items');

  // Skip room creation as rooms already exist
  console.log('✅ Skipped room creation (rooms already exist)');

  console.log('🎉 Database seed completed successfully!');
}

main()
  .catch((e) => {
    console.error('❌ Error seeding database:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
